# Generated by Django 4.1.7 on 2023-03-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Halaman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media/assets')),
                ('nama_web', models.CharField(max_length=100)),
                ('whatsapp', models.CharField(max_length=100)),
                ('wa_message', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=200)),
                ('gambar', models.ImageField(upload_to='media/products/')),
                ('deskripsi', models.CharField(max_length=200)),
                ('harga', models.IntegerField(default=None)),
            ],
        ),
    ]
