# Generated by Django 4.1.7 on 2023-03-28 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='total',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='updated_at',
        ),
    ]
