# Generated by Django 4.1.7 on 2023-03-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_contact_total_remove_contact_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='halaman',
            name='facebook',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='halaman',
            name='instagram',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='halaman',
            name='tentang_toko',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='nama_web',
            field=models.CharField(default='Store', max_length=100),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='wa_message',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='whatsapp',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='deskripsi',
            field=models.CharField(max_length=500),
        ),
    ]
