# Generated by Django 4.1.7 on 2023-03-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_remove_halaman_facebook_remove_halaman_instagram_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='halaman',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='halaman',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='halaman',
            name='country',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='halaman',
            name='facebook',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='halaman',
            name='instagram',
            field=models.URLField(default=None),
        ),
        migrations.AddField(
            model_name='halaman',
            name='phone',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='halaman',
            name='wa_message',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.AddField(
            model_name='halaman',
            name='zip',
            field=models.IntegerField(default=None),
        ),
    ]
