# Generated by Django 4.1.7 on 2023-03-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_halaman_address_halaman_city_halaman_country_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='count',
            field=models.IntegerField(default=None, max_length=200),
        ),
    ]
