# Generated by Django 4.1.7 on 2023-03-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_product_visitor_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visitor',
            field=models.IntegerField(default=None),
        ),
    ]
