# Generated by Django 4.1.7 on 2023-03-31 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_product_visitor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(default=None, max_length=200)),
                ('count', models.IntegerField(default=None)),
                ('created_at', models.DateField(default=None)),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='visitor',
        ),
    ]
