# Generated by Django 4.1.7 on 2023-03-31 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_visitor_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='visitor_product',
            field=models.IntegerField(default=None),
        ),
    ]
