# Generated by Django 4.1.7 on 2023-03-31 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_product_visitor_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitor',
            name='page',
        ),
    ]
