# Generated by Django 4.1.7 on 2023-03-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_remove_visitor_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='halaman',
            name='email',
            field=models.EmailField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
