# Generated by Django 4.1.7 on 2023-04-01 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_halaman_phone_alter_halaman_tentang_toko'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halaman',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='facebook',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='instagram',
            field=models.URLField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='wa_message',
            field=models.CharField(blank=True, default=None, max_length=500),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='zip',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='visitor_product',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
