# Generated by Django 4.1.7 on 2023-04-02 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_alter_halaman_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='key_words',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='profile'),
        ),
    ]
