# Generated by Django 4.1.7 on 2023-04-02 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_product_key_words_alter_halaman_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='halaman',
            name='key_words_page',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
