# Generated by Django 4.1.7 on 2023-04-02 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_alter_product_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gambar',
            field=models.ImageField(null=True, upload_to='products'),
        ),
    ]
