# Generated by Django 4.1.7 on 2023-04-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0031_alter_product_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gambar',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products'),
        ),
    ]
