# Generated by Django 4.1.7 on 2023-04-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_alter_product_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deskripsi',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='harga',
            field=models.IntegerField(blank=True, default=None),
        ),
    ]
