# Generated by Django 4.1.7 on 2023-04-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_alter_product_deskripsi_alter_product_harga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='nama',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
