# Generated by Django 4.1.7 on 2023-04-03 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_alter_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halaman',
            name='key_words_page',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
