# Generated by Django 4.1.7 on 2023-04-04 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0038_alter_halaman_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='halaman',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='city',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='facebook',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='instagram',
            field=models.URLField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='key_words_page',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='phone',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='tentang_toko',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='wa_message',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='halaman',
            name='zip',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
