# Generated by Django 4.1.7 on 2023-03-30 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_userextend_phone_alter_userextend_zip'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserExtend',
        ),
    ]
